console.log(null>0)
console.log(null>=0)
console.log(null<0)
console.log(null<=0)
console.log(null==0)
console.log(null===0)
console.log(null!=0)

console.log("\n")

console.log(undefined>0)
console.log(undefined>=0)
console.log(undefined<0)
console.log(undefined<=0)
console.log(undefined==0)
console.log(undefined===0)
console.log(undefined!=0)