let t = new Date()
console.log(t)
console.log(t.toString())
console.log(t.toDateString())
console.log(t.toLocaleString())
console.log(t.getDate())
console.log(t.getMonth())
console.log(t.getFullYear())
console.log(t.getDay())
console.log(t.toTimeString())
